Add item requests
Alechkasp/java-shareit pull request #3
Opened 2023-02-20 13:35 UTC by Alechkasp

2023-02-21 17:24 UTC, AnastasiyaFomkina requested changes

2023-02-21 17:24 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    private static final String HEADER = "X-Sharer-User-Id";
Лучше вынести хэдер в отдельный класс, например, `Variables`, и сделать публичной константой. Так мы избавимся от дублей и сможем переиспользовать код

2023-02-21 17:24 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestMapper.java
> +public class ItemRequestMapper {
_Саморазвитие_
В коммерческой разработке принято максимально избавляться от шаблонного кода, чтобы не перегружать и так большие и объемные проекты. Для маппинга сущностей часто используется библиотека [Mapstruct](https://blog.skillfactory.ru/glossary/mapstruct/), которая позволяет автоматически настраивать маппинг из одной сущности в другую с помощью описания интерфейсов и аннотаций.
Вот [здесь](https://www.baeldung.com/mapstruct) есть отличный гайд для старта работы с библиотекой.
При наличии свободного времени можно поизучать и попробовать прикрутить в проект

2023-02-21 17:24 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", 1))
Если сделать хэдер публичной константой и вынести его в отдельный класс, то можно будет использовать даже здесь

2023-02-21 17:24 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    private LocalDateTime end = start.plusDays(2);
`start` и `end` могут быть `final`

2023-02-21 17:24 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingMapperTest.java
> +class BookingMapperTest {
Лучше написать по одному тесту на каждый метод маппера

2023-02-21 17:24 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    ItemRepository itemRepository;
У параметров выше не хватает модификаторов доступа

2023-02-21 17:24 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    private LocalDateTime end = LocalDateTime.now();
`start` и `end` могут быть `final`

2023-02-21 17:24 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +class BookingServiceImplTest {
_Опционально_
Большие тесты очень удобно бить на подклассы с помощью аннотации `@Nested`. Так тест станет более структурированным и его будет проще читать.
Вот хорошая [статья](https://www.petrikainulainen.net/programming/testing/junit-5-tutorial-writing-nested-tests/) о том, как ей пользоваться

2023-02-21 17:24 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    private CreateCommentDto createCommentDto;
Нужно избавиться от переменных класса, которые нигде не используются (строки 46-49)

2023-02-21 17:24 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplIntegrationTest.java
> +    private UpdateItemDto updateItemDto;
Нигде не используется

2023-02-21 17:24 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplIntegrationTest.java
> +    private ItemDtoResponse itemDtoResponse;
Строки 59-60 можно сделать переменные методов, а не выносить в переменные класса

2023-02-21 17:24 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/request/ItemRequestServiceImplIntegrationTest.java
> +    private LocalDateTime created = LocalDateTime.now();
Может быть `final`

2023-02-21 17:24 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/request/ItemRequestServiceImplIntegrationTest.java
> +    private ItemRequest itemRequest;
30 и 31 лучше сделать переменными метода

2023-02-22 09:10 UTC, Alechkasp commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                        .header("X-Sharer-User-Id", 1))
Поправила

2023-02-22 09:10 UTC, Alechkasp commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    private LocalDateTime end = start.plusDays(2);
Поправила

2023-02-22 09:10 UTC, Alechkasp commented on src/test/java/ru/practicum/shareit/booking/BookingMapperTest.java
> +class BookingMapperTest {
Поправила

2023-02-22 09:11 UTC, Alechkasp commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    private static final String HEADER = "X-Sharer-User-Id";
Поправила

2023-02-22 09:11 UTC, Alechkasp commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestMapper.java
> +public class ItemRequestMapper {
Спасибо, обязательно посмотрю

2023-02-22 09:12 UTC, Alechkasp commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    ItemRepository itemRepository;
Поправила

2023-02-22 09:13 UTC, Alechkasp commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    private LocalDateTime end = LocalDateTime.now();
Поправила

2023-02-22 09:13 UTC, Alechkasp commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +class BookingServiceImplTest {
Поправила

2023-02-22 09:13 UTC, Alechkasp commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    private CreateCommentDto createCommentDto;
Поправила

2023-02-22 09:13 UTC, Alechkasp commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplIntegrationTest.java
> +    private UpdateItemDto updateItemDto;
Поправила

2023-02-22 09:14 UTC, Alechkasp commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplIntegrationTest.java
> +    private ItemDtoResponse itemDtoResponse;
Поправила

2023-02-22 09:14 UTC, Alechkasp commented on src/test/java/ru/practicum/shareit/request/ItemRequestServiceImplIntegrationTest.java
> +    private LocalDateTime created = LocalDateTime.now();
Поправила

2023-02-22 09:14 UTC, Alechkasp commented on src/test/java/ru/practicum/shareit/request/ItemRequestServiceImplIntegrationTest.java
> +    private ItemRequest itemRequest;
Поправила

2023-02-23 09:07 UTC, AnastasiyaFomkina approved these changes
Отличная работа, молодец 👍

2023-02-26 10:42 UTC, merged